import Foundation

struct PrototypeGenerator: Sendable {
    static let schemeName = "PrototypeApp"

    private let fileManager: SendableFileManager

    init(fileManager: FileManager = .default) {
        self.fileManager = SendableFileManager(fileManager)
    }

    func generate(_ record: HostProjectRecord, at projectURL: URL) throws {
        let sourcesURL = projectURL.appending(path: "Sources", directoryHint: .isDirectory)
        try fileManager.value.createDirectory(at: sourcesURL, withIntermediateDirectories: true)

        try write(
            "import ProjectDescription\n\nlet tuist = Tuist()\n",
            to: projectURL.appending(path: "Tuist.swift")
        )
        try write(projectManifest(for: record), to: projectURL.appending(path: "Project.swift"))
        try write(appSource(for: record), to: sourcesURL.appending(path: "PrototypeApp.swift"))
        try write(readme(for: record), to: projectURL.appending(path: "README.md"))
    }

    private func projectManifest(for record: HostProjectRecord) -> String {
        """
        import ProjectDescription

        let project = Project(
            name: "PrototypeApp",
            organizationName: "BuilderHost",
            targets: [
                .target(
                    name: "PrototypeApp",
                    destinations: .iOS,
                    product: .app,
                    bundleId: \(swiftLiteral(record.bundleIdentifier)),
                    deploymentTargets: .iOS("26.0"),
                    infoPlist: .extendingDefault(with: [
                        "CFBundleDisplayName": \(swiftLiteral(record.name)),
                        "UILaunchScreen": [:],
                    ]),
                    sources: ["Sources/**"],
                    settings: .settings(base: [
                        "SWIFT_VERSION": "6.0",
                        "SWIFT_STRICT_CONCURRENCY": "complete",
                        "TARGETED_DEVICE_FAMILY": "1,2",
                    ])
                ),
            ]
        )
        """
    }

    private func appSource(for record: HostProjectRecord) -> String {
        let prompt = record.prompt.isEmpty
            ? "This prototype is ready for its first prompt."
            : record.prompt
        return """
        import SwiftUI

        @main
        struct PrototypeApp: App {
            var body: some Scene {
                WindowGroup {
                    PrototypeView()
                }
            }
        }

        struct PrototypeView: View {
            var body: some View {
                NavigationStack {
                    ScrollView {
                        VStack(alignment: .leading, spacing: 20) {
                            Image(systemName: "hammer.fill")
                                .font(.system(size: 48))
                                .foregroundStyle(.tint)
                                .accessibilityHidden(true)

                            Text(\(swiftLiteral(record.name)))
                                .font(.largeTitle.bold())

                            Text(\(swiftLiteral(prompt)))
                                .font(.body)
                                .foregroundStyle(.secondary)

                            Label("Built on your Mac", systemImage: "checkmark.seal.fill")
                                .font(.headline)
                                .foregroundStyle(.green)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding(24)
                    }
                    .navigationTitle("Prototype")
                }
            }
        }
        """
    }

    private func readme(for record: HostProjectRecord) -> String {
        """
        # \(record.name)

        Generated by Builder Host. The source stays inside this controlled project directory.

        Bundle identifier: `\(record.bundleIdentifier)`
        """
    }

    private func write(_ contents: String, to url: URL) throws {
        guard let data = contents.data(using: .utf8) else {
            throw PrototypeGeneratorError.encodingFailed
        }
        try data.write(to: url, options: .atomic)
    }

    private func swiftLiteral(_ value: String) -> String {
        var escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\t", with: "\\t")
        escaped = escaped.unicodeScalars.reduce(into: "") { output, scalar in
            if scalar.value == 0x2028 || scalar.value == 0x2029 {
                output += "\\u{\(String(scalar.value, radix: 16))}"
            } else {
                output.unicodeScalars.append(scalar)
            }
        }
        return "\"\(escaped)\""
    }
}

enum PrototypeGeneratorError: LocalizedError, Equatable {
    case encodingFailed

    var errorDescription: String? { "Unable to encode the generated prototype source." }
}
